<script lang="ts" setup>
import type { WmsLocationInventoryGroup, WmsLocationInventoryQuery } from '#/api/wms';
import { reactive, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { getWmsLocationInventory } from '#/api/wms';
import { useErpAcctStore } from '#/store';
defineOptions({ name: 'WmsLocationInventory' });
const acct = useErpAcctStore(); const loading = ref(false); const groups = ref<WmsLocationInventoryGroup[]>([]); const open = ref<string[]>([]);
const form = reactive<WmsLocationInventoryQuery>({ erpAcctCode: acct.acctCode || '', erpOrgNumber: '', stockNumber: '', unallocatedOnly: false, diffOnly: false });
async function query(){if(!form.erpOrgNumber||!form.stockNumber)return ElMessage.warning('请输入 ERP 组织和仓库编码');loading.value=true;try{const res=await getWmsLocationInventory({...form,erpAcctCode:acct.acctCode||''});if(!res.success)throw new Error(res.message);groups.value=res.data.groups;open.value=groups.value.map((_,index)=>String(index));}catch(e:any){ElMessage.error(e.message||'查询失败');}finally{loading.value=false;}}
</script>
<template><div class="page"><h1>WMS库位库存</h1><p>展示 ERP 权威库存维度在 WMS 库位、容器和条码上的作业投影。</p><el-form inline><el-form-item label="ERP组织"><el-input v-model="form.erpOrgNumber" /></el-form-item><el-form-item label="仓库"><el-input v-model="form.stockNumber" /></el-form-item><el-form-item label="物料"><el-input v-model="form.materialCode" /></el-form-item><el-form-item label="仅未分配"><el-switch v-model="form.unallocatedOnly" /></el-form-item><el-form-item label="仅差异"><el-switch v-model="form.diffOnly" /></el-form-item><el-button type="primary" :loading="loading" @click="query">查询</el-button></el-form><el-collapse v-model="open"><el-collapse-item v-for="(group,index) in groups" :key="index" :name="String(index)"><template #title><span>{{ group.dimension.materialCode }} / {{ group.dimension.lotNo || '无批号' }}　ERP {{ group.erpQty }}　WMS {{ group.wmsQty }}　状态：{{ group.status }}</span></template><el-descriptions :column="4" border><el-descriptions-item label="ERP锁定">{{ group.erpLockedQty }}</el-descriptions-item><el-descriptions-item label="WMS预约">{{ group.wmsReservedQty }}</el-descriptions-item><el-descriptions-item label="数量差异">{{ group.qtyDiff }}</el-descriptions-item><el-descriptions-item label="锁定差异">{{ group.lockDiff }} {{ group.lockDiffReason }}</el-descriptions-item></el-descriptions><el-table :data="group.locations"><el-table-column prop="locationCode" label="库位"/><el-table-column prop="containerCode" label="容器"/><el-table-column prop="barcode" label="条码"/><el-table-column prop="qty" label="库位数量"/><el-table-column prop="reservedQty" label="WMS预约"/><el-table-column prop="availableQty" label="可作业量"/><el-table-column prop="operationStatus" label="作业状态"/></el-table></el-collapse-item></el-collapse></div></template>
<style scoped>.page{padding:20px;display:flex;flex-direction:column;gap:16px}</style>
