// Generated by scripts/status-dictionary.mjs. Do not edit manually.
export const DEFAULT_STATUS_LOCALE = "zh-CN" as const;

export interface BuiltinStatusEntry {
  code: string;
  domain: string;
  field: string;
  locale: string;
  text: string;
}

export const REGISTERED_STATUS_FIELDS = new Set<string>([
  "global.status",
  "productionReport.aggregateStatus",
  "productionReport.taskStatus",
  "wms.operationTaskStatus",
  "wms.inspectionStatus",
  "wms.reconcileStatus",
  "inspection.taskStatus",
  "inspection.erpPushStatus",
  "inspection.dispositionStatus",
  "inspection.returnStatus",
  "inspection.judgement",
  "materialTask.pickStatus",
  "materialTask.feedStatus",
  "materialTask.returnStatus",
  "productionInstock.taskStatus",
  "flowCard.status",
  "flowCard.claimStatus",
  "productionException.handlerStatus",
  "productionException.exceptionType",
  "processPool.status",
  "processRoute.status",
  "processWage.calcStatus",
  "erp.billStatus",
  "erp.auditExceptionStatus",
  "erp.auditExceptionType",
  "factory.resourceStatus",
  "feedback.status",
  "notification.level"
]);

export const BUILTIN_STATUS_ENTRIES: readonly BuiltinStatusEntry[] = [
  {
    "domain": "global",
    "field": "status",
    "code": "ACTIVE",
    "locale": "zh-CN",
    "text": "启用"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "INACTIVE",
    "locale": "zh-CN",
    "text": "停用"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ENABLED",
    "locale": "zh-CN",
    "text": "启用"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "DISABLED",
    "locale": "zh-CN",
    "text": "停用"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "NORMAL",
    "locale": "zh-CN",
    "text": "正常"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "PENDING",
    "locale": "zh-CN",
    "text": "待处理"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "APPLIED",
    "locale": "zh-CN",
    "text": "已申请"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "PREPARING",
    "locale": "zh-CN",
    "text": "备料中"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "PREPARED",
    "locale": "zh-CN",
    "text": "已备料"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "PREVIEWED",
    "locale": "zh-CN",
    "text": "已预览"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ISSUING",
    "locale": "zh-CN",
    "text": "发料中"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "READY",
    "locale": "zh-CN",
    "text": "准备就绪"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "DISPATCHED",
    "locale": "zh-CN",
    "text": "已下达"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "DRAFT",
    "locale": "zh-CN",
    "text": "草稿"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "CREATED",
    "locale": "zh-CN",
    "text": "已创建"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "SUBMITTED",
    "locale": "zh-CN",
    "text": "已提交"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "REVIEWING",
    "locale": "zh-CN",
    "text": "审核中"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "APPROVING",
    "locale": "zh-CN",
    "text": "审批中"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "APPROVED",
    "locale": "zh-CN",
    "text": "已审核"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "REJECTED",
    "locale": "zh-CN",
    "text": "已驳回"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "TERMINATED",
    "locale": "zh-CN",
    "text": "已终止"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "FROZEN",
    "locale": "zh-CN",
    "text": "已冻结"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "CLOSED",
    "locale": "zh-CN",
    "text": "已关闭"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "WAIT_CONFIRM",
    "locale": "zh-CN",
    "text": "待确认"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "PENDING_CONFIRM",
    "locale": "zh-CN",
    "text": "待确认"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "CONFIRMING",
    "locale": "zh-CN",
    "text": "确认中"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "CONFIRMED",
    "locale": "zh-CN",
    "text": "已确认"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "IN_PROGRESS",
    "locale": "zh-CN",
    "text": "进行中"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "PROCESSING",
    "locale": "zh-CN",
    "text": "处理中"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "RUNNING",
    "locale": "zh-CN",
    "text": "运行中"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "EXECUTING",
    "locale": "zh-CN",
    "text": "执行中"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "OPERATING",
    "locale": "zh-CN",
    "text": "作业中"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "COMPLETED",
    "locale": "zh-CN",
    "text": "已完成"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "DONE",
    "locale": "zh-CN",
    "text": "已完成"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "SUCCESS",
    "locale": "zh-CN",
    "text": "成功"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "FAILED",
    "locale": "zh-CN",
    "text": "失败"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "CANCELLED",
    "locale": "zh-CN",
    "text": "已取消"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "SKIPPED",
    "locale": "zh-CN",
    "text": "已跳过"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "EXPIRED",
    "locale": "zh-CN",
    "text": "已过期"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "FORBIDDEN",
    "locale": "zh-CN",
    "text": "无权限"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "PUSHING",
    "locale": "zh-CN",
    "text": "推送中"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "PUSHED",
    "locale": "zh-CN",
    "text": "已推送"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "PUSH_FAILED",
    "locale": "zh-CN",
    "text": "推送失败"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_FAILED",
    "locale": "zh-CN",
    "text": "ERP处理失败"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_PUSHED",
    "locale": "zh-CN",
    "text": "已推送ERP"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_STATUS_PENDING",
    "locale": "zh-CN",
    "text": "等待ERP处理"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_SYNCED",
    "locale": "zh-CN",
    "text": "ERP已同步"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_DRAFT",
    "locale": "zh-CN",
    "text": "ERP草稿"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_DRAFT_CREATED",
    "locale": "zh-CN",
    "text": "ERP草稿已创建"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_SUBMITTED",
    "locale": "zh-CN",
    "text": "ERP已提交"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_AUDITING",
    "locale": "zh-CN",
    "text": "ERP审核中"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_AUDITED",
    "locale": "zh-CN",
    "text": "ERP已审核"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_APPROVED",
    "locale": "zh-CN",
    "text": "ERP已审核"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_REJECTED",
    "locale": "zh-CN",
    "text": "ERP已驳回"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_TERMINATED",
    "locale": "zh-CN",
    "text": "ERP已终止"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_DELETED_OR_MISSING",
    "locale": "zh-CN",
    "text": "ERP单据不存在或已删除"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_REOPENED_OR_UNAUDITED",
    "locale": "zh-CN",
    "text": "ERP单据已反审核"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_CHANGED",
    "locale": "zh-CN",
    "text": "ERP单据已变更"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_POLL_FAILED",
    "locale": "zh-CN",
    "text": "ERP查询失败"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "ERP_POLL_TIMEOUT_PERMANENT",
    "locale": "zh-CN",
    "text": "ERP查询超时"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "WAIT_ERP_AUDIT",
    "locale": "zh-CN",
    "text": "等待ERP审核"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "WAIT_QC",
    "locale": "zh-CN",
    "text": "等待质检"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "WAIT_ROUTE",
    "locale": "zh-CN",
    "text": "等待工艺路线"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "CLAIMED",
    "locale": "zh-CN",
    "text": "已认领"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "TASK_CREATED",
    "locale": "zh-CN",
    "text": "任务已创建"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "WMS_POSTED",
    "locale": "zh-CN",
    "text": "WMS已过账"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "RESERVED",
    "locale": "zh-CN",
    "text": "已预占"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "RELEASED",
    "locale": "zh-CN",
    "text": "已释放"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "CONSUMED",
    "locale": "zh-CN",
    "text": "已消耗"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "BLOCKED",
    "locale": "zh-CN",
    "text": "已阻塞"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "TRANSFER_PENDING",
    "locale": "zh-CN",
    "text": "等待调拨"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "PENDING_INSPECTION",
    "locale": "zh-CN",
    "text": "待检验"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "INSPECTING",
    "locale": "zh-CN",
    "text": "检验中"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "INSPECTED",
    "locale": "zh-CN",
    "text": "已检验"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "PASS",
    "locale": "zh-CN",
    "text": "合格"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "FAIL",
    "locale": "zh-CN",
    "text": "不合格"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "PASSED",
    "locale": "zh-CN",
    "text": "已合格"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "CANCELED",
    "locale": "zh-CN",
    "text": "已取消"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "REWORK",
    "locale": "zh-CN",
    "text": "返工"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "SCRAP",
    "locale": "zh-CN",
    "text": "报废"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "NONE",
    "locale": "zh-CN",
    "text": "无"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "INFO",
    "locale": "zh-CN",
    "text": "提示"
  },
  {
    "domain": "global",
    "field": "status",
    "code": "WARNING",
    "locale": "zh-CN",
    "text": "警告"
  },
  {
    "domain": "productionReport",
    "field": "aggregateStatus",
    "code": "PUSHING",
    "locale": "zh-CN",
    "text": "生产汇报推送中"
  },
  {
    "domain": "productionReport",
    "field": "aggregateStatus",
    "code": "ERP_STATUS_PENDING",
    "locale": "zh-CN",
    "text": "等待ERP审核"
  },
  {
    "domain": "productionReport",
    "field": "aggregateStatus",
    "code": "ERP_AUDITED",
    "locale": "zh-CN",
    "text": "生产汇报已审核"
  },
  {
    "domain": "productionReport",
    "field": "aggregateStatus",
    "code": "INSPECTION_PUSHING",
    "locale": "zh-CN",
    "text": "产品入库检验推送中"
  },
  {
    "domain": "productionReport",
    "field": "aggregateStatus",
    "code": "INSPECTION_AUDITED",
    "locale": "zh-CN",
    "text": "产品入库检验已审核"
  },
  {
    "domain": "productionReport",
    "field": "aggregateStatus",
    "code": "PUSH_FAILED",
    "locale": "zh-CN",
    "text": "生产汇报推送失败"
  },
  {
    "domain": "productionReport",
    "field": "aggregateStatus",
    "code": "INSPECTION_FAILED",
    "locale": "zh-CN",
    "text": "产品入库检验失败"
  },
  {
    "domain": "productionReport",
    "field": "taskStatus",
    "code": "SOURCE_REVERSED",
    "locale": "zh-CN",
    "text": "来源已冲销"
  },
  {
    "domain": "flowCard",
    "field": "status",
    "code": "PENDING",
    "locale": "zh-CN",
    "text": "待开始"
  },
  {
    "domain": "flowCard",
    "field": "status",
    "code": "RUNNING",
    "locale": "zh-CN",
    "text": "进行中"
  },
  {
    "domain": "flowCard",
    "field": "status",
    "code": "IN_PROGRESS",
    "locale": "zh-CN",
    "text": "进行中"
  },
  {
    "domain": "flowCard",
    "field": "status",
    "code": "COMPLETED",
    "locale": "zh-CN",
    "text": "已完成"
  },
  {
    "domain": "flowCard",
    "field": "status",
    "code": "SKIPPED",
    "locale": "zh-CN",
    "text": "已跳过"
  },
  {
    "domain": "flowCard",
    "field": "claimStatus",
    "code": "CLAIMED",
    "locale": "zh-CN",
    "text": "已认领"
  },
  {
    "domain": "flowCard",
    "field": "claimStatus",
    "code": "RELEASED",
    "locale": "zh-CN",
    "text": "已释放"
  },
  {
    "domain": "flowCard",
    "field": "claimStatus",
    "code": "WAITING",
    "locale": "zh-CN",
    "text": "待认领"
  },
  {
    "domain": "productionException",
    "field": "handlerStatus",
    "code": "REPORTED",
    "locale": "zh-CN",
    "text": "已上报"
  },
  {
    "domain": "productionException",
    "field": "handlerStatus",
    "code": "HANDLING",
    "locale": "zh-CN",
    "text": "处理中"
  },
  {
    "domain": "productionException",
    "field": "handlerStatus",
    "code": "RESOLVED",
    "locale": "zh-CN",
    "text": "已解决"
  },
  {
    "domain": "productionException",
    "field": "handlerStatus",
    "code": "ESCALATED",
    "locale": "zh-CN",
    "text": "已升级"
  },
  {
    "domain": "productionException",
    "field": "exceptionType",
    "code": "EQUIPMENT",
    "locale": "zh-CN",
    "text": "设备故障"
  },
  {
    "domain": "productionException",
    "field": "exceptionType",
    "code": "MOULD",
    "locale": "zh-CN",
    "text": "模具异常"
  },
  {
    "domain": "productionException",
    "field": "exceptionType",
    "code": "GAUGE",
    "locale": "zh-CN",
    "text": "量具异常"
  },
  {
    "domain": "productionException",
    "field": "exceptionType",
    "code": "QUALITY",
    "locale": "zh-CN",
    "text": "质量异常"
  },
  {
    "domain": "productionException",
    "field": "exceptionType",
    "code": "ORDER",
    "locale": "zh-CN",
    "text": "工单异常"
  },
  {
    "domain": "productionException",
    "field": "exceptionType",
    "code": "OTHER",
    "locale": "zh-CN",
    "text": "其他异常"
  },
  {
    "domain": "wms",
    "field": "reconcileStatus",
    "code": "MATCHED",
    "locale": "zh-CN",
    "text": "已匹配"
  },
  {
    "domain": "wms",
    "field": "reconcileStatus",
    "code": "ERP_ONLY",
    "locale": "zh-CN",
    "text": "仅ERP存在"
  },
  {
    "domain": "wms",
    "field": "reconcileStatus",
    "code": "WMS_ONLY",
    "locale": "zh-CN",
    "text": "仅WMS存在"
  },
  {
    "domain": "wms",
    "field": "reconcileStatus",
    "code": "QTY_DIFF",
    "locale": "zh-CN",
    "text": "数量不一致"
  },
  {
    "domain": "wms",
    "field": "reconcileStatus",
    "code": "UNALLOCATED_ONLY",
    "locale": "zh-CN",
    "text": "仅存在未分配数量"
  },
  {
    "domain": "inspection",
    "field": "taskStatus",
    "code": "PENDING",
    "locale": "zh-CN",
    "text": "待检验"
  },
  {
    "domain": "inspection",
    "field": "taskStatus",
    "code": "IN_PROGRESS",
    "locale": "zh-CN",
    "text": "检验中"
  },
  {
    "domain": "inspection",
    "field": "taskStatus",
    "code": "COMPLETED",
    "locale": "zh-CN",
    "text": "检验完成"
  },
  {
    "domain": "inspection",
    "field": "taskStatus",
    "code": "CANCELLED",
    "locale": "zh-CN",
    "text": "已取消"
  },
  {
    "domain": "inspection",
    "field": "taskStatus",
    "code": "CANCELED",
    "locale": "zh-CN",
    "text": "已取消"
  },
  {
    "domain": "inspection",
    "field": "taskStatus",
    "code": "PASSED",
    "locale": "zh-CN",
    "text": "已合格"
  },
  {
    "domain": "inspection",
    "field": "erpPushStatus",
    "code": "WAIT_REPORT_AUDIT",
    "locale": "zh-CN",
    "text": "等待生产汇报审核"
  },
  {
    "domain": "inspection",
    "field": "erpPushStatus",
    "code": "WAIT_LOCAL_RESULT",
    "locale": "zh-CN",
    "text": "等待本地检验结果"
  },
  {
    "domain": "inspection",
    "field": "erpPushStatus",
    "code": "READY_TO_PUSH",
    "locale": "zh-CN",
    "text": "待推送产品入库检验"
  },
  {
    "domain": "inspection",
    "field": "erpPushStatus",
    "code": "SOURCE_INVALID",
    "locale": "zh-CN",
    "text": "生产汇报来源无效"
  },
  {
    "domain": "inspection",
    "field": "erpPushStatus",
    "code": "WAIT_R1",
    "locale": "zh-CN",
    "text": "等待生产汇报单"
  },
  {
    "domain": "inspection",
    "field": "erpPushStatus",
    "code": "PUSH_PENDING",
    "locale": "zh-CN",
    "text": "待下推"
  },
  {
    "domain": "inspection",
    "field": "erpPushStatus",
    "code": "PUSHING",
    "locale": "zh-CN",
    "text": "下推中"
  },
  {
    "domain": "inspection",
    "field": "erpPushStatus",
    "code": "PUSHED",
    "locale": "zh-CN",
    "text": "已下推"
  },
  {
    "domain": "inspection",
    "field": "erpPushStatus",
    "code": "PUSH_FAILED",
    "locale": "zh-CN",
    "text": "下推失败"
  },
  {
    "domain": "inspection",
    "field": "erpPushStatus",
    "code": "SKIPPED",
    "locale": "zh-CN",
    "text": "无需下推"
  },
  {
    "domain": "inspection",
    "field": "judgement",
    "code": "PENDING",
    "locale": "zh-CN",
    "text": "待判定"
  },
  {
    "domain": "inspection",
    "field": "judgement",
    "code": "PASS",
    "locale": "zh-CN",
    "text": "合格"
  },
  {
    "domain": "inspection",
    "field": "judgement",
    "code": "FAIL",
    "locale": "zh-CN",
    "text": "不合格"
  },
  {
    "domain": "inspection",
    "field": "judgement",
    "code": "NA",
    "locale": "zh-CN",
    "text": "不适用"
  },
  {
    "domain": "inspection",
    "field": "returnStatus",
    "code": "INSPECT_PASS_RETURN_TO_STOCK",
    "locale": "zh-CN",
    "text": "检验合格退回库存"
  },
  {
    "domain": "inspection",
    "field": "returnStatus",
    "code": "INSPECT_FAIL_TO_SCRAP",
    "locale": "zh-CN",
    "text": "检验不合格报废"
  },
  {
    "domain": "materialTask",
    "field": "pickStatus",
    "code": "PREPARING",
    "locale": "zh-CN",
    "text": "备料中"
  },
  {
    "domain": "materialTask",
    "field": "pickStatus",
    "code": "ISSUING",
    "locale": "zh-CN",
    "text": "发料中"
  },
  {
    "domain": "materialTask",
    "field": "returnStatus",
    "code": "INSPECT_FAIL_TO_VENDOR",
    "locale": "zh-CN",
    "text": "来料不良退供应商"
  },
  {
    "domain": "processRoute",
    "field": "status",
    "code": "DRAFT",
    "locale": "zh-CN",
    "text": "草稿"
  },
  {
    "domain": "processRoute",
    "field": "status",
    "code": "REVIEWING",
    "locale": "zh-CN",
    "text": "审核中"
  },
  {
    "domain": "processRoute",
    "field": "status",
    "code": "APPROVED",
    "locale": "zh-CN",
    "text": "已审核"
  },
  {
    "domain": "processRoute",
    "field": "status",
    "code": "ACTIVE",
    "locale": "zh-CN",
    "text": "已启用"
  },
  {
    "domain": "processRoute",
    "field": "status",
    "code": "DISABLED",
    "locale": "zh-CN",
    "text": "已失效"
  },
  {
    "domain": "processWage",
    "field": "calcStatus",
    "code": "WAIT_QUALITY",
    "locale": "zh-CN",
    "text": "待质检"
  },
  {
    "domain": "processWage",
    "field": "calcStatus",
    "code": "PENDING_REVIEW",
    "locale": "zh-CN",
    "text": "待复核"
  },
  {
    "domain": "processWage",
    "field": "calcStatus",
    "code": "AUDITED",
    "locale": "zh-CN",
    "text": "待推送ERP"
  },
  {
    "domain": "processWage",
    "field": "calcStatus",
    "code": "AUDIT_REJECTED",
    "locale": "zh-CN",
    "text": "主管驳回"
  },
  {
    "domain": "processWage",
    "field": "calcStatus",
    "code": "CONFIRMED",
    "locale": "zh-CN",
    "text": "待主管审核"
  },
  {
    "domain": "processWage",
    "field": "calcStatus",
    "code": "CONFIRM_REJECTED",
    "locale": "zh-CN",
    "text": "统计驳回"
  },
  {
    "domain": "processWage",
    "field": "calcStatus",
    "code": "CALCULATED",
    "locale": "zh-CN",
    "text": "已核算"
  },
  {
    "domain": "erp",
    "field": "auditExceptionStatus",
    "code": "OPEN",
    "locale": "zh-CN",
    "text": "待处理"
  },
  {
    "domain": "erp",
    "field": "auditExceptionStatus",
    "code": "PROCESSING",
    "locale": "zh-CN",
    "text": "处理中"
  },
  {
    "domain": "erp",
    "field": "auditExceptionStatus",
    "code": "RESOLVED",
    "locale": "zh-CN",
    "text": "已解决"
  },
  {
    "domain": "feedback",
    "field": "status",
    "code": "ACCEPTED",
    "locale": "zh-CN",
    "text": "已受理"
  },
  {
    "domain": "feedback",
    "field": "status",
    "code": "EVALUATING",
    "locale": "zh-CN",
    "text": "评估中"
  },
  {
    "domain": "feedback",
    "field": "status",
    "code": "DEVELOPING",
    "locale": "zh-CN",
    "text": "处理中"
  },
  {
    "domain": "inspection",
    "field": "dispositionStatus",
    "code": "PASS",
    "locale": "zh-CN",
    "text": "合格"
  },
  {
    "domain": "inspection",
    "field": "dispositionStatus",
    "code": "REWORK",
    "locale": "zh-CN",
    "text": "返修"
  },
  {
    "domain": "inspection",
    "field": "dispositionStatus",
    "code": "SCRAP",
    "locale": "zh-CN",
    "text": "报废"
  },
  {
    "domain": "inspection",
    "field": "dispositionStatus",
    "code": "PENDING",
    "locale": "zh-CN",
    "text": "待处置"
  },
  {
    "domain": "erp",
    "field": "billStatus",
    "code": "A",
    "locale": "zh-CN",
    "text": "已创建"
  },
  {
    "domain": "erp",
    "field": "billStatus",
    "code": "AUDITED",
    "locale": "zh-CN",
    "text": "已审核"
  },
  {
    "domain": "erp",
    "field": "billStatus",
    "code": "B",
    "locale": "zh-CN",
    "text": "审核中"
  },
  {
    "domain": "erp",
    "field": "billStatus",
    "code": "C",
    "locale": "zh-CN",
    "text": "已审核"
  },
  {
    "domain": "erp",
    "field": "billStatus",
    "code": "D",
    "locale": "zh-CN",
    "text": "重新审核"
  },
  {
    "domain": "erp",
    "field": "billStatus",
    "code": "DRAFT",
    "locale": "zh-CN",
    "text": "草稿"
  },
  {
    "domain": "erp",
    "field": "billStatus",
    "code": "FAILED",
    "locale": "zh-CN",
    "text": "失败"
  },
  {
    "domain": "erp",
    "field": "billStatus",
    "code": "SUBMITTED",
    "locale": "zh-CN",
    "text": "已提交"
  },
  {
    "domain": "erp",
    "field": "billStatus",
    "code": "Z",
    "locale": "zh-CN",
    "text": "暂存"
  }
];
