import { requestClient } from '#/api/request';

export type ProductionReportAggregateStatus = 'CANCELLED'|'ERP_AUDITED'|'ERP_STATUS_PENDING'|'INSPECTION_AUDITED'|'INSPECTION_FAILED'|'INSPECTION_PUSHING'|'PUSH_FAILED'|'PUSHING';
export interface ProductionReportAggregateCandidate { orderId:number; orderNo:string; erpAcctCode:string; erpOrgId?:string; workshopNumber?:string; erpSourceBillId?:number; erpSourceEntryId?:number; materialNumber?:string; materialName?:string; specification?:string; unitNumber?:string; reportQuantity:number; reportWorkSeconds:number; goodQuantity:number; defectQuantity:number; scrapQuantity:number; inspectionTotalQty?:string; qualifiedQty?:string; unqualifiedQty?:string; scrapQty?:string; remainingReportQty?:string; reportTaskIds:number[]; confirmable:boolean; blockedReason?:string; }
export interface ProductionReportAggregate { id:number; orderId:number; orderNo:string; erpAcctCode?:string; erpOrgId?:string; workshopNumber?:string; materialNumber?:string; materialName?:string; reportQuantity:number; reportWorkSeconds?:number; goodQuantity?:number; defectQuantity?:number; scrapQuantity?:number; inspectionTotalQty?:string; qualifiedQty?:string; unqualifiedQty?:string; scrapQty?:string; detailCount?:number; status:ProductionReportAggregateStatus; erpReportBillNo?:string; erpInspectionBillNo?:string; retryCount?:number; lastError?:string; }
export interface ProductionReportAggregateConfirmResult { orderId:number; erpSourceEntryId?:number; success:boolean; aggregateId?:number; status?:string; message?:string; }
export const getProductionReportAggregateCandidates=(params?:{orderNo?:string;erpAcctCode?:string;erpOrgId?:string})=>requestClient.get('/production-report-aggregates/candidates',{params,responseReturn:'body'});
export const getProductionReportAggregates=(params?:{orderNo?:string;status?:ProductionReportAggregateStatus})=>requestClient.get('/production-report-aggregates',{params,responseReturn:'body'});
export const getProductionReportAggregateDetails=(id:number)=>requestClient.get(`/production-report-aggregates/${id}/details`,{responseReturn:'body'});
export const confirmProductionReportAggregates=(items:unknown[])=>requestClient.post('/production-report-aggregates/confirm',{items},{responseReturn:'body'});
export const retryProductionReportAggregate=(id:number)=>requestClient.post(`/production-report-aggregates/${id}/retry`,undefined,{responseReturn:'body'});
export const cancelProductionReportAggregate=(id:number,reason?:string)=>requestClient.post(`/production-report-aggregates/${id}/cancel`,{reason},{responseReturn:'body'});
